source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'AFSAppDispatcherKit_Example' do
  
  use_frameworks!
  
  pod 'AFSAppDispatcherKit', :path => '../'

  target 'AFSAppDispatcherKit_Tests' do
    inherit! :search_paths
  end
end
